- name: 'download nginx docker image (on master), this can take a moment...'
  docker_image:
    name: "{{ nginx_image }}"
    tag: "{{ nginx_tag }}"
    force_source: "{{ force_pull_image | default('no') }}"
    source: pull
  notify:
    - restart nginx
  register: download_image_status
  until: download_image_status is succeeded
  retries: 2
  delay: 5
  run_once: yes
  delegate_to: "{{ groups['fullnode']|first }}"
  when:
    - images_from_master is defined
    - images_from_master|bool == True

- name: 'download nginx docker image, this can take a moment...'
  docker_image:
    name: "{{ nginx_image }}"
    tag: "{{ nginx_tag }}"
    force_source: "{{ force_pull_image | default('no') }}"
    source: pull
  notify:
    - restart nginx
  register: download_image_status
  until: download_image_status is succeeded
  retries: 2
  delay: 5
  when: >
        images_from_master is not defined or
        images_from_master|bool == False

- name: set image name and tag
  set_fact:
    this_tag: "{{ nginx_tag }}"
    this_image: "{{ nginx_image }}"

- name: set temporary image file name
  set_fact:
    this_file: "/tmp/image-nginx-{{ this_tag }}.tar"

- name: image export and load block
  block:

    - name: check image exists
      shell: "/usr/bin/docker images {{ this_image }}:{{ this_tag }} | grep -q '^{{ this_image }}'"
      changed_when: False
      register: image_stat
      failed_when: "image_stat.rc > 1"

    - name: export the image to a file
      delegate_to: "{{ groups['fullnode']|first }}"
      docker_image:
        name: "{{ this_image }}"
        tag: "{{ this_tag }}"
        archive_path: "{{ this_file }}"
      when: "image_stat.rc == 1"

    - name: copy the docker image from the first node
      synchronize:
        src: "{{ this_file }}"
        dest: "{{ this_file }}"
      when: image_stat.rc == 1
      register: image_copied

    - name: load the image into docker
      docker_image:
        name: "{{ this_image }}"
        tag: "{{ this_tag }}"
        load_path: "{{ this_file }}"
        source: load
      when:
        - image_copied.changed
      notify:
        - restart nginx

  when:
    - groups['fullnode'] | length > 1
    - inventory_hostname != groups['fullnode']|first

- name: remove image from temporary location
  file:
    path: "{{ this_file }}"
    state: absent
