- name: set variables centos/redhat
  set_fact:
    systemd_dir: /usr/lib/systemd/system
    config_dir: /etc/sysconfig
  when: ansible_distribution == 'CentOS'

- name: set variables debian/ubuntu
  set_fact:
    systemd_dir: /etc/systemd/system
    config_dir: /etc/default
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: add user to run field as
  user:
    name: "{{ field_username }}"
    shell: /sbin/nologin
    createhome: no
    home: "{{ field_dir }}"
  tags:
    - field_user

- name: get field user uid
  shell: "echo -n $(id -u {{ field_username }})"
  changed_when: false
  register: field_uid

- name: create field home directory
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ field_username }}"
    group: "{{ field_username }}"
    mode: 0700
  with_items:
    - "{{ field_dir }}"
    - "{{ field_configdir }}"
  tags:
    - field_dirs

# can override with "-e my_field_name=my-unique-name"
- name: generate my_field_name
  set_fact:
    my_field_name: "playbook_{{ ansible_fqdn | to_uuid |  truncate(8, True, '') }}"
  tags:
    - field_name

- name: copy field config
  template:
    src: templates/config.ini.j2
    dest: "{{ field_configdir }}/config.ini"
    force: "{{ overwrite | default('no') }}"
    backup: yes
  tags:
    - field_config
  notify:
    - restart field

- name: copy sysconfig file
  template:
    src: templates/field.sysconfig.j2
    dest: "{{ config_dir }}/field"
    force: "{{ overwrite | default('no') }}"
    backup: yes
  notify:
    - restart field

- name: copy systemd service file
  template:
    src: templates/field.service.j2
    dest: "{{ systemd_dir }}/field.service"
  notify:
    - restart field

- name: 'download field images, this can take a moment...'
  docker_image:
    name: "{{ field_image }}"
    tag: "{{ field_tag }}"
    force: "{{ force_pull_image | default('no') }}"    
  tags:
    - field_docker_image
  notify:
    - restart field

- name: flush handlers
  meta: flush_handlers

- name: ensure field started and enabled
  systemd:
    name: field.service
    state: started
    enabled: yes

- name: pause for 3 seconds to get field ID
  pause:
    seconds: 3

- name: Field ID for field_exporter
  block:

    - name: check field ID file
      stat:
        path: "{{ field_dir }}/.deviota-field.id"
      register: field_id_file

    - name: get field ID from file
      shell: "cat {{ field_dir }}/.deviota-field.id | head -c${1:-16}"
      register: field_id_read
      changed_when: false

    - name: set fact field ID
      set_fact:
        field_public_id: "{{ field_id_read.stdout }}"

    - name: update field-exporter config
      template:
        src: ../shared-files/field-exporter.config.js.j2
        dest: "{{ field_exporter_configdir }}/config.js"
        owner: "{{ prom_username }}"
        group: "{{ prom_username }}"
        backup: yes
      notify:
        - restart field-exporter

  tags:
    - field_exporter
  ignore_errors: yes
