- import_tasks: deps.yml
  tags:
    - field_deps

- import_tasks: firewall.yml
  tags:
    - field_firewall
  when: configure_firewall is defined and configure_firewall|bool == True

- import_tasks: field.yml
  tags:
    - field_config

- import_tasks: uninstall.yml
  tags:
    - uninstall
    - uninstall_field
  when: uninstall_playbook is defined and uninstall_playbook|bool == True
