- name: Stop field service
  systemd:
    name: field
    state: stopped
    enabled: false
  ignore_errors: yes

- name: remove field tcp port in firewall
  firewalld:
    port: "{{ field_tcp_port }}/tcp"
    permanent: true
    state: disabled
    immediate: yes
  when: ansible_distribution == 'CentOS'

- name: remove field tcp port in firewall
  ufw:
    rule: allow
    direction: in
    proto: tcp
    port: "{{ field_tcp_port }}"
    delete: yes
  when: ansible_distribution == 'Ubuntu'

- name: set variables centos/redhat
  set_fact:
    systemd_dir: /usr/lib/systemd/system
    config_dir: /etc/sysconfig
  when: ansible_distribution == 'CentOS'

- name: set variables debian/ubuntu
  set_fact:
    systemd_dir: /etc/systemd/system
    config_dir: /etc/default
  when: ansible_distribution == 'Ubuntu'

- name: remove field files
  file:
    path: "{{ item }}"
    state: absent
  notify:
    - reload systemd
  with_items:
    - "{{ systemd_dir }}/field.service"
    - "{{ config_dir }}/field"

- name: remove field user
  user:
    name: "{{ field_username }}"
    state: absent
