- name: ensure firewalld started and enabled
  systemd:
    name: firewalld
    state: started
    enabled: yes
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

- name: allow nelson tcp port in firewall
  firewalld:
    port: "{{ nelson_tcp_port }}/tcp"
    permanent: true
    state: enabled
    immediate: yes
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

- name: allow nelson tcp port in firewall
  ufw:
    rule: allow
    direction: in
    proto: tcp
    port: "{{ nelson_tcp_port }}"
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
