- name: firewalld block
  block:

    - name: remove nelson tcp port in firewall
      firewalld:
        port: "{{ item }}/tcp"
        permanent: true
        state: disabled
        immediate: yes
      with_items:
        - "{{ nelson_tcp_port }}"
        - "{{ nelson_gui_port }}"

    - name: remove nelson gui proxy port via selinux seport
      seport:
        ports: "{{ nelson_gui_port }}"
        proto: tcp
        setype: http_port_t
        state: absent

  when:
    - ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

- name: remove nelson tcp ports from firewall
  ufw:
    rule: allow
    direction: in
    proto: tcp
    delete: yes
    port: "{{ item }}"
  with_items:
    - "{{ nelson_tcp_port }}"
    - "{{ nelson_gui_port }}"
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: set variables centos/redhat
  set_fact:
    systemd_dir: /usr/lib/systemd/system
    config_dir: /etc/sysconfig
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

- name: set variables debian/ubuntu
  set_fact:
    systemd_dir: /etc/systemd/system
    config_dir: /etc/default
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'


- name: remove nelson
  block:

    - name: Stop any active nelson service
      systemd:
        name: "{{ item }}"
        state: stopped
        enabled: false
      ignore_errors: yes
      with_items:
        - nelson
        - nelson-gui

    - name: Remove current nelson packages
      npm:
        name: "{{ item }}"
        global: yes
        state: absent
      with_items:
        - nelson.cli
        - nelson.gui

- name: remove nelson related files
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "{{ nelson_configdir }}"
    - "{{ nelson_datadir }}"
    - "{{ config_dir }}/nelson-gui"

- name: remove nelson systemd files
  file:
    path: "{{ systemd_dir }}/{{ item }}"
    state: absent
  notify:
    - reload systemd
  with_items:
    - nelson.service
    - nelson-gui.service

- name: remove nelson user
  user:
    name: "{{ nelson_username }}"
    state: absent
