grafana_username: grafana
grafana_image: grafana/grafana
grafana_tag: 6.5.1
grafana_port: "3000"
grafana_bind_address: 127.0.0.1
grafana_proxy_port: "5555"
grafana_configdir: /etc/grafana
grafana_basedir: /var/lib/grafana
grafana_provisioning_path: "{{ grafana_configdir }}/provisioning"
grafana_dashboards_path: "{{ grafana_basedir }}/dashboards"
