# The tcp port on which iota-pm will be served
iotapm_port: 8011

# IOTA-pm image
iotapm_image: nuriel77/iota-pm

# IOTA-pm tag
iotapm_tag: latest

# The address on which iota-pm will served
# Use 0.0.0.0 for all interfaces
iotapm_bind_address: 127.0.0.1

# The port to serve iota PM on the webserver
iotapm_proxy_port: 8811

# Run IOTA Peer Manager as this user
iotapm_username: iotapm

# If setting `iotapm_bind_address` to anything other than
# localhost (127.0.0.1) should the port be opened in firewall
# Can be `true` or `false`
iotapm_allow_firewall: false

# Unprivileged username with which to run iota-pm.
# Will be created if doesn't exist
iotapm_username: iotapm
