# Unprivileged user to run iri with
iri_username: iri

# Base directory where iri is installed and runs from
iri_basedir: /var/lib/iri

# The iri version to install
iri_version: 1.5.1

# The TCP port on which IRI listens for API calls and allows for light wallets to connect to
iri_api_port: 14265

# The UDP neighbor peering port
iri_udp_port: 14600

# The TCP neighbor peering port
iri_tcp_port: 14600

# IRI ZMQ port
iri_zmq_port: 5556

# IRI ZMQ enabled (extra metrics from IRI)
iri_zmq_enabled: true

# Set openfiles limit
iri_open_files_limit: 65535

# Limit IRI memory usage
iri_java_mem: 4096m

# Initial memory usage
iri_init_java_mem: 1024m

# IRI memory heap size Xmn
iri_java_heap_mem: 1024m

# Exclude the commands below from the API.
# Applied only to connections other than localhost/127.0.0.1
iri_remote_limit_api: "removeNeighbors, addNeighbors, interruptAttachingToTangle, attachToTangle, getNeighbors"

# Let the iri_api_port bind to all interfaces (0.0.0.0).
# `true` is necessary in order to allow external wallets/APIs to connect without tunneling.
# If set to `false` it will only bind to localhost (127.0.0.1)
api_port_remote: false

# The RPM version to download, check http://www.oracle.com/technetwork/java/javase/downloads/jdk8-downloads-2133151.html
oracle_java_rpm: 'http://download.oracle.com/otn-pub/java/jdk/8u181-b13/96a7b8442fe848ef90c96a2fad6ed6d1/jdk-8u181-linux-x64.rpm'

# The version to download for Ubuntu
oracle_java_tar: 'http://download.oracle.com/otn-pub/java/jdk/8u181-b13/96a7b8442fe848ef90c96a2fad6ed6d1/jdk-8u181-linux-x64.tar.gz'

# Java oracle directory
oracle_java_dir: jdk1.8.0_181
