# Unprivileged user to run iri with
iri_username: iri

# Base directory where iri is installed and runs from
iri_basedir: /var/lib/iri

# IRI configuration dir
iri_configdir: /etc/iri

# IRI docker image
iri_image: iotaledger/iri

# The iri version to install
iri_version: 1.7.0

# IRI Docker image tag/version
iri_tag: "v{{ iri_version }}"

# Set to true for testnet, false for mainnet.
iri_testnet: false

# The TCP port on which IRI listens for API calls and allows for light wallets to connect to
iri_api_port: 14265

# The UDP neighbor peering port
iri_udp_port: 14600

# The TCP neighbor peering port
iri_tcp_port: 15600

# IRI ZMQ port
iri_zmq_port: 5556

# IRI ZMQ bind address
iri_zmq_bind: 127.0.0.1

# IRI ZMQ enabled (extra metrics from IRI)
iri_zmq_enabled: true

# Set openfiles limit
iri_open_files_limit: 65535

# Limit IRI memory usage
iri_java_mem: 4096m

# Initial memory usage
iri_init_java_mem: 1024m

# IRI memory heap size Xmn
iri_java_heap_mem: 1024m

# A network will be created in docker for iri
iri_net_name: iri_net
 
# Exclude the commands below from the API.
# Applied only to connections other than localhost/127.0.0.1
iri_remote_limit_api: "removeNeighbors, addNeighbors, getNeighbors"

# Let the iri_api_port bind to all interfaces (0.0.0.0).
# `true` is necessary in order to allow external wallets/APIs to connect without tunneling.
# If set to `false` it will only bind to localhost (127.0.0.1)
api_port_remote: false

# When using distributed LB
# Haproxy stats port with https
haproxy_stats_https: false

# Load balancer max connections (all backends)
lb_max_connections: 720

# Allowed concurrent connections to all iri backends
# (pow and default)
haproxy_iri_max_connections: 360

# Allowed concurrent connections to PoW backend
max_connections_pow_backend: 180

# Allowed concurrent connection to default backend (no PoW)
max_connections_backend: 180

# Enable remote auth with password.
# This will only allow connections using basic auth.
haproxy_remote_auth: false
