# Enable nelson installation
# NOTE: Nelson is in alpha pre-release
nelson_enabled: false

# User name under which to run nelson
nelson_username: nelson

# Nelson configuration directory
nelson_configdir: /etc/nelson

# Nelson data dir
nelson_datadir: /var/lib/nelson

# IRI host on which to bind to IRI
nelson_iri_host: 127.0.0.1

# Nelson bind API to this address
nelson_bind_address: 127.0.0.1

# Nelson API port
nelson_api_port: 18600

# Nelson communication TCP port
nelson_tcp_port: 16600

# Nelson gui port
nelson_gui_port_internal: 6611

# Nelson gui port
nelson_gui_port: 6600

# Nelson gui fallback version to install
# If latest version fails, this is the latest
# known version to install without breaking
nelson_gui_version: 0.2.9
