- name: set variables centos/redhat
  set_fact:
    systemd_dir: /usr/lib/systemd/system
    config_dir: /etc/sysconfig
  when: ansible_distribution == 'CentOS'
  tags:
    - nbctl_config

- name: set variables debian/ubuntu
  set_fact:
    systemd_dir: {{ systemd_dir }}
    config_dir: /etc/default
  when: ansible_distribution == 'Ubuntu'

- name: stop grafana
  systemd:
    name: grafana-server
    state: stopped
    enabled: false
  ignore_errors: yes

- name: remove proxy ports in firewall for monitoring services
  firewalld:
    port: "{{ item }}/tcp"
    permanent: true
    state: disabled
    immediate: yes
  with_items:
    - "{{ prom_proxy_port }}"
    - "{{ grafana_proxy_port }}"
    - "{{ alertmanager_proxy_port }}"
  when: ansible_distribution == 'CentOS'

- name: remove prometheus grafana proxy port via selinux seport
  seport:
    ports: "{{ item }}"
    proto: tcp
    setype: http_port_t
    state: absent
  with_items:
    - "{{ prom_proxy_port }}"
    - "{{ grafana_proxy_port }}"
    - "{{ alertmanager_proxy_port }}"
  when: ansible_distribution == 'CentOS'

- name: remove prometheus and grafana proxy port from firewall
  ufw:
    rule: allow
    direction: in
    proto: tcp
    port: "{{ item }}"
    delete: yes
  with_items:
    - "{{ prom_proxy_port }}"
    - "{{ grafana_proxy_port }}"
    - "{{ alertmanager_proxy_port }}"
  when: ansible_distribution == 'Ubuntu'

- name: stop monitoring services
  systemd:
    name: "{{ item }}"
    enabled: false
    state: stopped
  ignore_errors: yes
  with_items:
    - prometheus
    - alertmanager
    - iota-prom-exporter
    - prom-am-executor
    - node-exporter
    - field-exporter

- name: remove monitoring service files
  file:
    path: "{{ item }}"
    state: absent
  notify:
    - reload systemd
  with_items:
    - '{{ systemd_dir }}/prometheus.service'
    - '{{ systemd_dir }}/node-exporter.service'
    - '{{ systemd_dir }}/alertmanager.service'
    - "{{ systemd_dir }}/field-exporter.service"
    - '{{ systemd_dir }}/prom-am-executor.service'
    - '{{ systemd_dir }}/iota-prom-exporter.service'
    - "{{ config_dir }}/iota-prom-exporter"
    - "{{ config_dir }}/prometheus"
    - "{{ config_dir }}/alertmanager"
    - "{{ config_dir }}/node-exporter"

- name: remove monitoring related files and paths
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "{{ prom_basedir }}"
    - "{{ prom_datadir}}"
    - "{{ prom_configdir }}"
    - '/etc/rsyslog.d/node_exporter.conf'

- name: remove provisioning, datasources and dashboards directories
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "{{ grafana_provisioning_path }}"
    - "{{ grafana_dashboards_path }}"

- name: remove prometheus user
  user:
    name: "{{ prom_username }}"
    state: absent
