# --- CentOS
- name: Install epel-release
  yum:
    state: latest
    name: epel-release

- name: Install some packages
  yum:
    name: "{{ packages }}"
  vars:
    packages:
      - git
      - policycoreutils-python
      - libappindicator
      - firewalld
      - curl
      - wget
      - lsof
      - jq
      - pv
      - nano
      - sysstat
      - atop
      - htop
      - fpaste
      - openssl
      - util-linux
      - python-pip
      - python-passlib
      - httpd-tools
      - python-pip
      - ansible
  tags:
    - scripts
    - deps
