# --- Ubuntu

# Required, else jq and some other packages fail
- name: Update all packages to the latest version
  apt:
    upgrade: dist

- name: Install software-properties-common
  apt: state=latest name=software-properties-common update_cache=yes

- name: apt add repository
  apt_repository:
    repo: 'ppa:webupd8team/java'
    state: present

- name: debian | ensure the webupd8 launchpad apt repository key is present
  apt_key:
    id=0xC2518248EEA14886
    keyserver=keyserver.ubuntu.com
    state=present

- name: set license as accepted
  debconf:
    name: 'oracle-java8-installer'
    question: 'shared/accepted-oracle-license-v1-1'
    value: 'true'
    vtype: 'select'

- name: Install some packages
  apt: state=latest name={{ item }} update_cache=yes
  with_items:
    - maven
    - jq
    - ufw
    - oracle-java8-installer
    - wget
    - lsof
    - curl
    - pv
    - nano
    - sysstat
    - atop
    - htop

- name: Install oracle-java8-set-default
  apt: state=latest name=oracle-java8-set-default update_cache=yes

- name: set java home environment
  lineinfile:
    path: /etc/environment
    regexp: '^JAVA_HOME'
    line: 'JAVA_HOME="/usr/lib/jvm/java-8-oracle"'
