- name: allow iri tcp port in firewall
  ufw:
    rule: allow
    direction: in
    proto: tcp
    port: "{{ iri_tcp_port }}"

- name: allow iri udp port in firewall
  ufw:
    rule: allow
    direction: in
    proto: udp
    port: "{{ iri_udp_port }}"

# Allow direct access to IRI API port
# from other nodes in the cluster.
# This is only done when deploying
# multiple nodes.
- name: allow iri api port in firewall
  ufw:
    rule: allow
    direction: in
    proto: tcp
    port: "{{ iri_api_port }}"
    from_ip: "{{ item }}"
  with_items: "{{ groups['fullnode'] | map('extract', hostvars, ['ip']) | list | difference([ip]) }}"
  when:
    - groups['fullnode'] | length > 1
    - api_port_remote is defined
    - api_port_remote|bool == True
  tags:
    - expose_api_for_lb
    - consul_role

- name: allow ssh port firewall
  ufw:
    rule: allow
    direction: in
    proto: tcp
    port: "{{ ssh_port }}"

- name: ufw default outgoing policy allowed
  ufw:
    direction: outgoing
    policy: allow

- name: ensure ufw started and default incoming policy denied
  ufw:
    state: enabled
    direction: incoming
    policy: deny
