- name: allow iri tcp port in firewall
  ufw:
    rule: allow
    direction: in
    proto: tcp
    port: "{{ iri_tcp_port }}"

- name: allow iri udp port in firewall
  ufw:
    rule: allow
    direction: in
    proto: udp
    port: "{{ iri_udp_port }}"

- name: ufw iri port
  block:
    - name: allow iri api port in firewall
      ufw:
        rule: allow
        direction: in
        proto: tcp
        port: "{{ iri_api_port }}"
        log: yes

    # ufw supports connection rate limiting, which is useful for protecting
    # against denial of service attacks. ufw will deny connections if an IP
    # address has attempted to initiate 6 or more connections in the last
    # 30 seconds. See  http://www.debian-administration.org/articles/187
    # for details.
    - name: rate limit iri api port in firewall
      ufw:
        rule: limit
        direction: in
        proto: tcp
        port: "{{ iri_api_port }}"
        log: yes

  when: api_port_remote is defined and api_port_remote

- name: allow ssh port firewall
  ufw:
    rule: allow
    direction: in
    proto: tcp
    port: "{{ ssh_port }}"

- name: ufw default outgoing policy allowed
  ufw:
    direction: outgoing
    policy: allow

- name: ensure ufw started and default incoming policy denied
  ufw:
    state: enabled
    direction: incoming
    policy: deny
