- import_tasks: deps.yml
  tags:
    - iotapm_deps

- import_tasks: firewall.yml
  tags:
    - iotapm_firewall
  when: configure_firewall is defined and configure_firewall|bool == True

- import_tasks: iotapm.yml
  tags:
    - iotapm_config

- import_tasks: uninstall.yml
  tags:
    - uninstall
    - uninstall_iotapm
  when: uninstall_playbook is defined and uninstall_playbook|bool == True
