- name: remove iota-pm tcp ports in firewall
  firewalld:
    port: "{{ item }}"
    permanent: true
    state: disabled
    immediate: yes
  with_items:
    - "{{ iotapm_port }}/tcp"
    - "{{ iotapm_proxy_port }}/tcp"
  when: ansible_distribution == 'CentOS'

- name: remove iota-pm tcp port in firewall
  ufw:
    rule: allow
    direction: in
    proto: tcp
    delete: yes
    port: "{{ item }}"
  with_items:
    - "{{ iotapm_proxy_port }}"
    - "{{ iotapm_port }}"
  when: ansible_distribution == 'Ubuntu'

- name: set variables centos
  set_fact:
    systemd_dir: /usr/lib/systemd/system
    config_dir: /etc/sysconfig
  when: ansible_distribution == 'CentOS'

- name: set variables ubuntu
  set_fact:
    systemd_dir: /etc/systemd/system
    config_dir: /etc/default
  when: ansible_distribution == 'Ubuntu'

- name: stop iotapm
  systemd:
    name: iota-pm
    state: stopped
    enabled: false
  ignore_errors: yes

- name: remove systemd service file
  file:
    path: "{{ systemd_dir }}/iota-pm.service"
    state: absent
  notify:
    - reload systemd

- name: remove the user for iotapm
  user:
    name: "{{ iotapm_username }}"
    state: absent
    remove: yes

- name: remove iotapm related files
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "/var/spool/iotapm"
    - "{{ config_dir }}/iota-pm"

- name: remove container
  docker_container:
    name: "iota-pm"
    state: absent
  ignore_errors: yes

- name: remove iotapm image
  docker_image:
    state: absent
    force: yes
    name: "{{ iotapm_image }}"
    tag: "{{ iotapm_tag }}"
  ignore_errors: yes
