- name: restart grafana
  systemd:
    name: grafana-server.service
    daemon_reload: yes
    state: restarted
    enabled: yes

- name: restart prometheus
  systemd:
    name: prometheus.service
    daemon_reload: yes
    state: restarted
    enabled: yes

- name: reload prometheus
  systemd:
    name: prometheus.service
    state: reloaded

- name: restart alertmanager
  systemd:
    name: alertmanager.service
    daemon_reload: yes
    state: restarted
    enabled: yes

- name: restart iota-prom-exporter
  systemd:
    name: iota-prom-exporter.service
    daemon_reload: yes
    state: restarted
    enabled: yes

- name: restart field-exporter
  systemd:
    name: field-exporter.service
    daemon_reload: yes
    state: restarted
    enabled: yes

- name: restart node-exporter
  systemd:
    name: node-exporter.service
    daemon_reload: yes
    state: restarted
    enabled: yes

- name: restart prom-am-executor
  systemd:
    name: prom-am-executor.service
    daemon_reload: yes
    state: restarted
    enabled: yes
